"""Initial conditions and analytic helpers for equatorial Kerr orbits.

The numerical spacetime kernel lives in ``src.kerr_schild``.  This module
contains higher-level initial-condition helpers used by validation notebooks.

Conventions
-----------
- Geometrized units G = c = 1.
- Metric signature (-,+,+,+).
- Positive ``a`` means black-hole spin in the +z direction.
- ``sense=+1`` denotes prograde motion for a > 0.
- ``sense=-1`` denotes retrograde motion for a > 0.
"""

import math
import numpy as np

from .kerr_schild import metric_cov, kerr_radius


def circular_omega(r, M=1.0, a=0.5, sense=+1):
    """Exact equatorial circular Kerr angular velocity dphi/dt.

    Parameters
    ----------
    r : float
        Kerr/Boyer-Lindquist radial coordinate.
    M : float
        Black-hole mass in geometrized units.
    a : float
        Kerr spin parameter.
    sense : {+1, -1}
        +1 for prograde, -1 for retrograde (for a > 0).
    """
    if sense not in (+1, -1):
        raise ValueError("sense must be +1 (prograde) or -1 (retrograde)")

    sqrtM = math.sqrt(M)
    return sense * sqrtM / (r**1.5 + sense*a*sqrtM)


def circular_equatorial_state(r, M=1.0, a=0.5, sense=+1, phi0=0.0):
    """Return an exact equatorial circular timelike Kerr state.

    For circular motion dr=dtheta=0, Boyer-Lindquist time and azimuthal
    velocities are unchanged by the r-dependent transformation to
    Kerr-Schild time/azimuth.

    The Cartesian Kerr-Schild ring at fixed equatorial r obeys
        x^2 + y^2 = r^2 + a^2.
    We parameterize it by the axial Killing angle phi.
    """
    omega = circular_omega(r, M=M, a=a, sense=sense)

    R = math.sqrt(r*r + a*a)
    x = R * math.cos(phi0)
    y = R * math.sin(phi0)
    z = 0.0

    # Coordinate velocities dx^i/dt generated by the axial Killing vector.
    vx = -y * omega
    vy =  x * omega
    vz = 0.0

    g = metric_cov(x, y, z, M, a)

    # ds^2/dtau^2 = -1 = (u^t)^2 *
    # [g_tt + 2 g_ti v^i + g_ij v^i v^j].
    q = (
        g[0, 0]
        + 2.0*(g[0, 1]*vx + g[0, 2]*vy + g[0, 3]*vz)
        + g[1, 1]*vx*vx
        + g[2, 2]*vy*vy
        + g[3, 3]*vz*vz
        + 2.0*g[1, 2]*vx*vy
        + 2.0*g[1, 3]*vx*vz
        + 2.0*g[2, 3]*vy*vz
    )

    if q >= 0.0:
        raise ValueError(
            "Requested circular worldline is not timelike at these parameters."
        )

    ut = 1.0 / math.sqrt(-q)

    state = np.array(
        [
            0.0,
            x, y, z,
            ut,
            ut*vx,
            ut*vy,
            ut*vz,
        ],
        dtype=float,
    )

    # Internal consistency check: the requested Kerr radial coordinate
    # should be recovered from Cartesian coordinates.
    recovered_r = kerr_radius(x, y, z, a)
    if not math.isclose(recovered_r, r, rel_tol=1e-12, abs_tol=1e-12):
        raise RuntimeError("Cartesian initial point does not recover requested r.")

    return state


def zamo_omega_equator(r, M=1.0, a=0.5):
    """Angular velocity of a zero-angular-momentum observer at the equator.

    Omega_ZAMO = -g_{t phi} / g_{phi phi}.
    """
    R = math.sqrt(r*r + a*a)
    x, y, z = R, 0.0, 0.0

    g = metric_cov(x, y, z, M, a)

    # Axial Killing vector xi_phi^mu = (0, -y, x, 0).
    xi_x = -y
    xi_y = x

    g_tphi = g[0, 1]*xi_x + g[0, 2]*xi_y
    g_phiphi = (
        g[1, 1]*xi_x*xi_x
        + 2.0*g[1, 2]*xi_x*xi_y
        + g[2, 2]*xi_y*xi_y
    )

    return -g_tphi / g_phiphi
